services:
  app:
    image: neosmemo/memos:$VERSION
    restart: always
    depends_on:
      - db
    environment:
      MEMOS_DRIVER: "postgres"
      MEMOS_DSN: "user=$DB_USERNAME password=$DB_PASSWORD dbname=$DB_NAME host=$DB_HOST sslmode=disable"
    networks:
      - proxy
      - local

  db:
    image: postgres:16.1
    restart: always
    volumes:
      - "data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    networks:
      - local

volumes:
  data:

networks:
  local:
  proxy:
    external: true