services:
  app:
    image: neosmemo/memos:$VERSION
    restart: always
    environment:
      MEMOS_DRIVER: $DB_DRIVER
      MEMOS_DSN: "user=$DB_USERNAME password=$DB_PASSWORD dbname=$DB_NAME host=$DB_HOST sslmode=disable"
    networks:
      - proxy

networks:
  proxy:
    external: true