services:
  app:
    image: neosmemo/memos:$VERSION
    restart: always
    environment:
      MEMOS_DRIVER: $DB_DRIVER
      MEMOS_DSN: "$DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST)/$DB_NAME"
    networks:
      - proxy

networks:
  proxy:
    external: true