services:
  app:
    image: 'jc21/nginx-proxy-manager:$VERSION'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      # Postgres parameters:
      DB_POSTGRES_HOST: 'db'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: $DB_USERNAME
      DB_POSTGRES_PASSWORD: $DB_PASSWORD
      DB_POSTGRES_NAME: $DB_NAME
      INITIAL_ADMIN_EMAIL: $INITIAL_ADMIN_EMAIL
      INITIAL_ADMIN_PASSWORD: $INITIAL_ADMIN_PASSWORD
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    depends_on:
      - db
    networks:
      - proxy
      - local

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - local

volumes:
  data:
  letsencrypt:
  db_data:

networks:
  local:
  proxy:
    external: true
